services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - caddy=${TIPI_DOMAIN:-tipi.localhost}
      - caddy.reverse_proxy={{upstreams 80}}

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data
      - ./backend/pb_migrations:/pb/pb_migrations:ro
    labels:
      - caddy=pb.${TIPI_DOMAIN:-tipi.localhost}
      - caddy.reverse_proxy={{upstreams 8090}}

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    environment:
      - CADDY_INGRESS_NETWORKS=tipi_default

volumes:
  pb_data:
  caddy_data:
