// This file is a manual route tree (normally auto-generated by TanStack Router CLI)
// Run `npx tsr generate` to regenerate after adding routes

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'
import { RootLayout } from './routes/__root'
import { LandingPage } from './routes/index'
import { LoginPage } from './routes/auth/login'
import { RegisterPage } from './routes/auth/register'
import { HouseholdSetupPage } from './routes/auth/household-setup'
import { AppLayout } from './routes/app/_layout'
import { HomePage } from './routes/app/home'
import { TasksPage } from './routes/app/tasks'
import { ShoppingPage } from './routes/app/shopping'
import { ExpensesPage } from './routes/app/expenses'
import { DocumentsPage } from './routes/app/documents'
import { ProfilePage } from './routes/app/profile'

export const rootRoute = createRootRoute({ component: RootLayout })

export const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: LandingPage
})

export const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/login',
  component: LoginPage
})

export const registerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/register',
  component: RegisterPage
})

export const householdSetupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/setup',
  component: HouseholdSetupPage
})

export const appRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/app',
  component: AppLayout
})

export const homeRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/',
  component: HomePage
})

export const tasksRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/tasks',
  component: TasksPage
})

export const shoppingRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/shopping',
  component: ShoppingPage
})

export const expensesRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/expenses',
  component: ExpensesPage
})

export const documentsRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/documents',
  component: DocumentsPage
})

export const profileRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/profile',
  component: ProfilePage
})

export const routeTree = rootRoute.addChildren([
  indexRoute,
  loginRoute,
  registerRoute,
  householdSetupRoute,
  appRoute.addChildren([
    homeRoute,
    tasksRoute,
    shoppingRoute,
    expensesRoute,
    documentsRoute,
    profileRoute
  ])
])
